[owner]
name = "fzs"
password = "dongfengyang070313"

[[databases]]
sid = "cwdb"
host = "10.6.13.1"
sql_type = "ALL"

[[databases]]
sid = "bpdb"
host = "10.6.13.1"
sql_type = "ArchAndDBCap"

[[databases]]
sid = "fsywdb"
host = "10.6.14.1"
sql_type = "ALL"

[[databases]]
sid = "odsdb"
host = "10.6.12.21"
sql_type = "UserAndDBCap"

[[databases]]
sid = "o19chx"
host = "10.6.12.11"
sql_type = "ALL"

[[databases]]
sid = "o19cfs"
host = "10.6.12.11"
sql_type = "UserAndDBCap"

[[databases]]
sid = "o19cbp"
host = "10.6.12.51"
sql_type = "UserAndDBCap"

[[databases]]
sid = "o19cww"
host = "10.6.12.51"
sql_type = "ALL"

[[databases]]
sid = "checks"
host = "10.6.12.21"
sql_type = "OnlyDBCap"

[[databases]]
sid = "olap"
host = "10.6.12.21"
sql_type = "UserAndDBCap"

[[databases]]
sid = "cognos"
host = "10.6.12.21"
sql_type = "OnlyDBCap"

[sql]
user_cap = "select owner,round(sum(bytes/1024/1024/1024),0) from dba_segments where owner in ('ZYIC','BP','GL','HPM','APPLSYS','DZHXP','ATS','SIP_PJBJ','JYDB','ZYWMD','JZZF','ZYICEC','ECOLOGY','ILOG','PLATFORM','NYXLINK','SALES','AGRI','ZYICECIF','BI','EASTRPT','BDDJ3','EASTDW','ZBJ') group by owner order by 2 desc"
db_cap = "select round(sum(bytes/1024/1024/1024),0) total_gb from dba_segments"
arch_avg_cap = "select round(avg(round(sum(a.blocks * a.block_size) / 1024 / 1024 / 1024, 0)),0) arch_avg_cap from v$archived_log a, v$database b where a.completion_time>sysdate-31 group by b.name, to_char(a.completion_time, 'yyyy-mm-dd')"